### ISSUE TITLE
Auto-Build based of a Excel List every day?

### ISSUE THREAD

**Issue by enaske** [qtPyDev/wow_BlacklistTracker#11]
Hey,

since Github has this auto Build Feature. How about creating a Google Form for the Moderators / Staff of the Discord Servers.

For example a simple form contain:

Name
Server
Ban-Reason
Link to the BanPost

And once a day, Github could rebuild the User-List from the given Google Drive Document (which is prob. a Table, that so I assume can be scrapped by API)

That would keep the List up2date and People can also get the Link to the Banpost Ingame, so they can Copy / Paste it. 

Not sure if Auto-Push to CurseForge could be done as a Final Step, so people can just Update the Addon with Curse Client.

**Comment by squidsoup** [comment]
This is a nice idea, and certainly an improvement over the hardcoded blacklists. If the author is amenable to the idea, I could have a go at writing a python script that would fetch and translate the data to a lua dictionary. @enaske do you think a form would be preferable to a shared access Google spreadsheet? If you're submitting batches of blacklists on a cadence it might be easier to edit rows in sheets?

**Comment by qtPyDev** [comment]
Marking this as closed as there is already a backend in development that will automate the process. It will rely on bots and on a DB to scrape and store the data, with frequent builds. Any questions, please contact.

Marked as resolved.

**Comment by squidsoup** [comment]
@qtPyDev is that an oss project as well? Are you accepting contributions for the backend?
